# Generated by Django 5.0.4 on 2024-07-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
