# Generated by Django 5.0.4 on 2024-07-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="version",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
