# Generated by Django 5.0.4 on 2024-07-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "permissions": [
                    ("cancel_publish_product", "Может отменять публикацию продукта"),
                    ("change_product_description", "Может менять описание продукта"),
                    ("change_product_category", "Может менять категорию продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
